### ISSUE TITLE
What license is your code?

### ISSUE THREAD

**Issue by lazyzero** [treguly/pico-hid#1]
Hi,

can you tell me what license is your code?

Best Christian

**Comment by treguly** [comment]
I didn't even really think of that, just wanted to share it.

**Comment by lazyzero** [comment]
Hi,

I fully understand that, but sharing without license, is considered as proprietary software. Here is the link to the [Choose a License](https://choosealicense.com), a service from github to select a license. Often used for circuitpython projects is the  [MIT license](https://choosealicense.com/licenses/mit/).

Best Christian

**Comment by treguly** [comment]
I've added a license, apologies for the delay.
